#pragma once

#define Touch_GPIO_RST      (36)
#define Touch_GPIO_INT      (42)

#define I2C_GPIO_SCL        (46)
#define I2C_GPIO_SDA        (45)

#define H_size              (800)
#define V_size              (480)

#define LCD_CLK_MHZ         (18)
#define LCD_HPW             ( 4)
#define LCD_HBP             ( 8)
#define LCD_HFP             ( 8)
#define LCD_VPW             ( 4)
#define LCD_VBP             (16)
#define LCD_VFP             (16)

#define LCD_GPIO_RST        (-1)
#define RGB_PIN_NUM_DISP_EN (-1)
#define RGB_PIN_NUM_HSYNC   (40)
#define RGB_PIN_NUM_VSYNC   (41)
#define RGB_PIN_NUM_DE      ( 2)
#define RGB_PIN_NUM_PCLK    ( 3)

#define RGB_PIN_NUM_DATA0   ( 8)
#define RGB_PIN_NUM_DATA1   ( 7)
#define RGB_PIN_NUM_DATA2   ( 6)
#define RGB_PIN_NUM_DATA3   ( 5)
#define RGB_PIN_NUM_DATA4   ( 4)
#define RGB_PIN_NUM_DATA5   (14)
#define RGB_PIN_NUM_DATA6   (13)
#define RGB_PIN_NUM_DATA7   (12)
#define RGB_PIN_NUM_DATA8   (11)
#define RGB_PIN_NUM_DATA9   (10)
#define RGB_PIN_NUM_DATA10  ( 9)
#define RGB_PIN_NUM_DATA11  (19)
#define RGB_PIN_NUM_DATA12  (18)
#define RGB_PIN_NUM_DATA13  (17)
#define RGB_PIN_NUM_DATA14  (16)
#define RGB_PIN_NUM_DATA15  (15)

#define WIFI_HOSTED_SDIO_PIN_CMD    (54)
#define WIFI_HOSTED_SDIO_PIN_CLK    (53)
#define WIFI_HOSTED_SDIO_PIN_D0     (52)
#define WIFI_HOSTED_SDIO_PIN_D1     (51)
#define WIFI_HOSTED_SDIO_PIN_D2     (50)
#define WIFI_HOSTED_SDIO_PIN_D3     (49)
#define WIFI_HOSTED_SDIO_PIN_RESET  (20)

#define SD_GPIO_MMC_CLK     (43)
#define SD_GPIO_MMC_CMD     (44)
#define SD_GPIO_MMC_D0      (39)

#define SPK_I2S_LRCK_GPIO   (21)
#define SPK_I2S_BCLK_GPIO   (22)
#define SPK_I2S_SDOUT_GPIO  (23)

#define PIN_SPI_SCK         (26)
#define PIN_SPI_MOSI        (48)
#define PIN_SPI_MISO        (47)
#define LORA_RESET          (32)
#define LORA_DIO1           (31)
#define LORA_BUSY           (29)
#define LORA_CS             (30)
